### ISSUE TITLE
p2 bootstrap download url broken on maven repo

### ISSUE THREAD

**Issue by k-brooks** [diffplug/goomph#101]
With 3.17.6, specifically d63ddb6fe26f34cbbd018547919fea418231ff4c, the process used to download the p2 bootstrap binary was changed.
The move introduced/exposed a few bugs.
1. The FileMisc.download method does not verify the content or the response code, it will dump the body of the response to the provided file.
2. I don't believe the FileNotFoundException fallback handling will ever be reached, and that issue may extend beyond problem 1 - I suspect the new library handles 404's differently.
3. The subsequent unzip of the 404 content proceeds without issue (or any output I can find)

I created https://gist.github.com/k-brooks/eca39b22aba3c5dcc791cdf4000b0633 to highlight issues 1 and 3. You'll need to update the p2BootstrapUrl to a maven style repo in order to exercise 2.

**Comment by nedtwigg** [comment]
Fixed in `3.20.0`
