### ISSUE TITLE
Support gradle buildship

### ISSUE THREAD

**Issue by moley** [diffplug/goomph#103]
Hi, 

I tried the addProjectFolder() method to import projects. I work with buildship plugin, so I don't have eclipse plugin in my projects applied and I do not have a .project file created. This is somehow created by buildship plugin importing the project as gradle project. It would be nice if one could import a project without having a .project file before. 

Cheers
Markus

**Comment by nedtwigg** [comment]
I'm not a buildship expert, but I think it slurps the project structure entirely from the `build.gradle`, so none of Goomph's standard-project-import stuff will work.  For this usecase, Goomph is helpful for setting up an IDE with the right installed components, but the IDE will start off empty, and you'll have to manually import the project on first usage.

To make this entirely automatic, you'd need to create subclass of [`SetupAction`](https://github.com/diffplug/goomph/blob/master/src/main/java/com/diffplug/gradle/oomph/SetupAction.java) (which runs inside the generated IDE on startup to call the custom Buildship import API), and then add the action to the installation inside of [`ConventionBuildship`](https://github.com/diffplug/goomph/blob/master/src/main/java/com/diffplug/gradle/oomph/thirdparty/ConventionBuildship.java).  I'd be happy to merge a PR for this, but would be a tricky job.  Probably not many LOC, but each line will be tricky.

**Comment by nedtwigg** [comment]
Related: #87 and #15.

**Comment by nedtwigg** [comment]
[EquoIDE](https://github.com/equodev/equo-ide/tree/main/plugin-gradle) implemented this in

- https://github.com/equodev/equo-ide/pull/76
