### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by frankbenoit** [diffplug/goomph#107]
Hello Ned,

on the front page of goomph, all those links pointing to JavaDoc (e.g. excludebuildfolder) are returning 404.

Frank

**Comment by nedtwigg** [comment]
Yup, sorry about that, #105 will fix, which I'm planning to do for the next eclipse release.  When a bad link opens, replace `3.18.1` with `3.18.0` and it will fix it.  Sorry for the hiccup
