### ISSUE TITLE
Any means to indicate what Goomph is downloading on Eclipse?

### ISSUE THREAD

**Issue by Baytars** [diffplug/goomph#133]
Really I appreciate your work because your effors may make my dream of developing hybrid application of both maven-managed projects and Eclipse components support (e.g. SWT browser with Saxon XSLT 3.0 support), a feature that Tycho failed to achieve, come into reality. Eclipse has a fascinating ecosystem worth exploring but its components on mvnrepository.com are too old to be utilized and I got none of them sufficient of dependencies of their required versions.

Though, something is still scratchy for me and I wish that you feel the same way, too.

The p2AsMaven downloaded for over 20 min for a single IU for me but I could't figure out what it was downloading and how much dependencies still remained to download. The IDEA IDE told me Gradle was configuring the project, my speed indicator indicated download speed at about 100K/s but nothing more I can learn about. It doesn't take such long when I install the plugin in Eclipse.

At last the download finished and I saw that under `build/p2asmaven/p2/eclipse-deps/plugins` there were only a few jars.

Read a closed issue that Goomph may possibly download over 10G of data and was shocked. So I eagerly want to know in the console output what jar files Goomph is downloading for me and how much accumulated disk space they are going to consume. I wonder if this idea is ever feasible.

Still you did a great job in lowering the barrier and just keep going on!

**Comment by nedtwigg** [comment]
Progress reporting is a huge problem, but goomph just shells out to eclipse, so there's no way to fix it on the goomph side.
