### ISSUE TITLE
Oomph preferences passed in via goomph

### ISSUE THREAD

**Issue by dscowan** [diffplug/goomph#14]
I didn't really see anything regarding this in the docs.  I would like to use oomph record preferences and the inject those into goomph.  An example would be enabling line numbers in the editor. Is there a recommended way to do this?

**Comment by nedtwigg** [comment]
At present, there is no support for Oomph's recorded preferences, but I'd love to help add it.

The only way to modify preferences for now is to copy-paste the workspace, set the preference you want, and then diff the current workspace against the other to see what properties get set.

Then you can use `workspaceProp('filename', props -> { props.put('key', 'value') }` anywhere inside the `oomphIde` block to set other preferences.

[Here's an example](https://github.com/diffplug/goomph/blob/master/src/main/java/com/diffplug/gradle/oomph/ConventionStyle.java).

**Comment by dscowan** [comment]
The example above should be

 workspaceProp('filename', { props -> props.put('key', 'value') }

Fought that way to long.  This did get me what I needed.  It would be nice to be able to use oomphs recorded preferences.

**Comment by nedtwigg** [comment]
Agreed!  I'd need some help from Oomph guys, but they're understandably busy.

http://dev.eclipse.org/mhonarc/lists/oomph-dev/msg00143.html
https://www.eclipse.org/forums/index.php/t/1072047/
