### ISSUE TITLE
Configuration with name 'compile' not found.

### ISSUE THREAD

**Issue by gucchy55** [diffplug/goomph#151]
I got the following error when running gradle command:

> An exception occurred applying plugin request [id: 'com.diffplug.swt.nativedeps', version: '3.30.0']
> Failed to apply plugin 'com.diffplug.swt.nativedeps'.
   > Configuration with name 'compile' not found.

Environments:

- Gradle 7.1
- JVM: 16.0.1
- java: openjdk 16.0.1
- OS: Mac OS X 11.4 x86_64

build.gradle:

```gradle
plugins {
  id 'com.diffplug.swt.nativedeps' version '3.30.0'
}

repositories {
  mavenCentral()
}

apply plugin: 'java'
```

It was no problem with 'com.diffplug.swt.nativedeps' version '3.27.0' or older and gradle 6.x.
What is the problem?

**Comment by nedtwigg** [comment]
See changelog entry for [3.28.0](https://github.com/diffplug/goomph/blob/main/CHANGES.md#3280---2021-02-12). I would recommend migrating from `com.diffplug.swt.nativedeps` to [`com.diffplug.eclipse.mavencentral`](https://javadoc.io/static/com.diffplug.gradle/goomph/3.28.0/com/diffplug/gradle/eclipse/MavenCentralPlugin.html).

**Comment by gucchy55** [comment]
"com.diffplug.eclipse.mavencentral" works fine! Thank you for your help.
