### ISSUE TITLE
FileMisc throws an unexpected exception when a download fails

### ISSUE THREAD

**Issue by yohoe** [diffplug/goomph#152]
`FileMisc.download(..)` throws an `IllegalArgumentException` when a download fails (e.g. 404), but `PdeInstallation` and `P2BootstrapInstallation` expect it to throw `FileNotFoundExcpetion` in order to try alternative uris.

Workaround in my case is to append the version to `goomph_override_p2bootstrapUrl` so that the first try is successful, but this is less flexible.

**Comment by nedtwigg** [comment]
Thanks for reporting, PR's welcome.

**Comment by nedtwigg** [comment]
The EquoIDE plugins use `okhttp` instead of the janky FileMisc stuff, this issue is almost certain solved if you migrate to `dev.equo.ide` or `dev.equo.p2deps`. https://github.com/equodev/equo-ide/tree/main/plugin-gradle
