### ISSUE TITLE
p2AsMaven execution conflicts when Clean task is included in the execution task list

### ISSUE THREAD

**Issue by gkgeorgiev** [diffplug/goomph#165]
Currently, if you have ``clean`` task in the execution, this will clean the default root folder of the p2AsMaven plugin (the build directory). Which of course impacts the dependencies resolution right after.
A work-around would be to set a custom directory location, outside of Build, which is not ideal since it would be nice to avoid polluting the project with too many temporary folders. 

One proposed solution is to change the plugin from listening on gradle Configuration events, to a task, which is chained right before classpath dependencies task for instance. 

In any case, the default behavior should be something that works well with default settings, which is not currently the case.

**Comment by nedtwigg** [comment]
PR's welcome.

**Comment by bric3** [comment]
Hi, I found this issue by chance, I'm using gradle-intellij-plugin, and they have to download their own JDK runtime. However they don't store the archive or runtime in the project but in the gradle cache. Maybe that's something that may interest you ?

```
tree /Users/brice.dutheil/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_14_1-osx-x64-b2043.25/

/Users/brice.dutheil/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr_jcef-11_0_14_1-osx-x64-b2043.25/
├── 7f7978684a90a8d04d48029a686e8891f3a18562
│   └── jbre-jbr_jcef-11_0_14_1-osx-x64-b2043.25.tar.gz
└── extracted
    ├── jbr
    │   └── Contents
    │       ├── CodeResources
    │       ├── Frameworks
    │       │   ├── Chromium Embedded Framework.framework
    │       │   │   ├── Chromium Embedded Framework
...
    │       ├── Home
    │       │   ├── bin
    │       │   │   ├── jaotc
    │       │   │   ├── java
    │       │   │   ├── javac
    │       │   │   ├── jcmd
...
```

**Comment by nedtwigg** [comment]
This is solved in [`dev.equo.p2deps`](https://github.com/equodev/equo-ide/tree/main/plugin-gradle#user-plugins).
