### ISSUE TITLE
Multiple workspaceProp calls with the same file cause some properties not to be applied

### ISSUE THREAD

**Issue by scottresnik** [diffplug/goomph#17]
Simple build with the following:
```groovy
  oomphIde {
    style {
      niceText()		// nice fonts and visible whitespace
    }
   workspaceProp(".metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs", { props -> props.put('lineNumberRuler', 'true') })
  }
```
Only the line number ruler setting will be applied, but no white space will be visible.  If the line number setting is commented out, then the white space setting will be applied.

**Comment by nedtwigg** [comment]
Thanks for PR!  Fixed "multiple calls" bug in 86d207b52f19584c9603b0bccb4b8694620769f0, and added lineNumber support (thanks for finding the keys!) in a38398e17f80e9e06ce44ad9892e5ec07331b9c6.  Available in 3.6.0-SNAPSHOT once the CI build finishes.
