### ISSUE TITLE
java.lang.NoSuchFieldException: ucp

### ISSUE THREAD

**Issue by mfriesen** [diffplug/goomph#182]
Using the following build.gradle
plugins {
  id "com.diffplug.oomph.ide" version "3.35.0"
}

apply plugin: 'com.diffplug.oomph.ide'
oomphIde {
        repoEclipseLatest()
        jdt {}
        splash rootProject.file('_images/spotless_logo.png')
        style {
                classicTheme()  // oldschool cool
                niceText()              // nice fonts and visible whitespace
        }

        addAllProjects()

        thirdParty {
                minimalistGradleEditor {}
                //tmTerminal {}
        }
}

After running: gradle ide

Get Error:
> Task :ideSetupP2 FAILED
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ideSetupP2'.
> java.lang.NoSuchFieldException: ucp

Caused by: java.lang.NoSuchFieldException: ucp
        at com.diffplug.gradle.JRE.getClasspath(JRE.java:57)
        at com.diffplug.gradle.eclipserunner.JarFolderRunner.open(JarFolderRunner.java:62)
        at com.diffplug.gradle.eclipserunner.JarFolderRunner.run(JarFolderRunner.java:47)
        at com.diffplug.gradle.eclipserunner.JarFolderRunnerExternalJvm$RunOutside.run(JarFolderRunnerExternalJvm.java:126)
        at com.diffplug.gradle.JavaExecable.main(JavaExecable.java:171)

Gradle:  7.4.1
openjdk: 11.0.2

**Comment by nedtwigg** [comment]
Sorry, but the `oomph.ide` part of this project is mostly abandoned. I'm happy to merge PRs for it, and I won't intentionally break it, but the only active part of this project now is the `eclipse.mavencentral` plugin.

**Comment by restlessronin** [comment]
I'm getting the same exception when I try to use 'equinoxLaunch'

**Comment by nedtwigg** [comment]
Happy to take a PR for fixing Java 16+.

**Comment by restlessronin** [comment]
If I just use the same fix as used in the PR I linked above, it's only a few lines of code.

Unfortunately, I'm completely unfamiliar with the workflow for building and testing a gradle plugin, and I'm a little wary of starting down that particular rabbit hole at the moment.

Let me make the changes (that shouldn't take much time) and open a PR. You can decide if it's worth testing and merging.

**Comment by restlessronin** [comment]
I found this:  https://github.com/diffplug/goomph/blob/f49fa797b535986812924e4b24d3ec417a281b5c/CONTRIBUTING.md.

Hopefully, it's as easy to do as it seems :-)

**Comment by nedtwigg** [comment]
Attempted fix in `3.37.1`.

**Comment by restlessronin** [comment]
equinoxLaunch is no longer stopping there (still not working fully :-), so at least that's fixed.
