### ISSUE TITLE
`equinoxLaunch` : `java.lang.IllegalStateException: Unable to acquire application service.`...

### ISSUE THREAD

**Issue by restlessronin** [diffplug/goomph#196]
... `Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).`

How do I set the start level of the bundle?

**Comment by nedtwigg** [comment]
Inside `bundles.info`, I think: https://jmini.github.io/blog/2022/2022-02-09_bundlesinfo.html

**Comment by nedtwigg** [comment]
For issues like this I would recommend Solstice https://github.com/equodev/equo-ide/tree/main/solstice
