### ISSUE TITLE
No documentation for "dev.equo.p2deps"

### ISSUE THREAD

**Issue by dhakehurst** [diffplug/goomph#209]
There is a recommendation to use "dev.equo.p2deps" instead of p2asmaven

but no documentation regarding how to use it or how to convert.

**Comment by nedtwigg** [comment]
Thanks for the feedback, I responded at

- https://github.com/equodev/equo-ide/issues/158

**Comment by dhakehurst** [comment]
> how to convert

is the key part here.

https://github.com/equodev/equo-ide/issues/158 gives very minimal example on usage.
But nothing about how to convert.

e.g. how to convert this?
```
p2AsMaven {
        destination(p2asmavenDir)
        group("eclipse") {
            repo("http://download.eclipse.org/releases/2020-03/202003181000")
            repo("http://download.eclipse.org/sphinx/releases/0.11.x")
            this.iu("org.eclipse.emf.ecore")
            this.iu("org.eclipse.sphinx.emf")
        }
}
```

**Comment by nedtwigg** [comment]
I think this will do it:

```gradle
p2deps {
  into 'api', {
    p2repo 'http://download.eclipse.org/releases/2020-03/202003181000'
    p2repo 'http://download.eclipse.org/sphinx/releases/0.11.x'
    install 'org.eclipse.emf.ecore'
    install 'org.eclipse.sphinx.emf'
  }
}
```

Key thing to note is that with `p2deps` there is no "conversion" into maven. That's why you don't need to set `destination(p2asmavenDir)`, the p2 deps are cached as p2. Same with the artificial `group("eclipse")`.

**Comment by nedtwigg** [comment]
Sorry, didn't mean to close it! Let me know if this works for you.

**Comment by dhakehurst** [comment]
why does it break the standard gradle approach of defining a repository and then allowing projects to add dependencies as required. ?

the old p2AsMaven approach was better!

**Comment by nedtwigg** [comment]
I'm not going to delete `p2AsMaven`, and I will continue to merge PRs for it. But it has been difficult to maintain - pretending that p2 was maven was a harder problem (imo) than "put these p2 jars on the classpath", which cuts out a leaky translation from p2 to maven. My own projects have all switched to `p2deps`, and it's been an improvement for my workflows. Happy to merge PRs in either project (Goomph or Equo) if they help with yours :)

**Comment by dhakehurst** [comment]
OK, thanks for the response anyway.

**Comment by dhakehurst** [comment]
ah....we don't replace the 'p2AsMaven' section.

we replace the 'dependencies' section.

i.e.

```
p2AsMaven {
        destination(p2asmavenDir)
        group("eclipse") {
            repo("http://download.eclipse.org/releases/2020-03/202003181000")
            repo("http://download.eclipse.org/sphinx/releases/0.11.x")
            this.iu("org.eclipse.emf.ecore")
            this.iu("org.eclipse.sphinx.emf")
        }
}

dependencies {
  api("eclipse:org.eclipse.sphinx.platform:+")
  api("eclipse:org.eclipse.emf.ecore:+")
  ...
}

```

becomes

```
p2deps {
  into 'api', {
    p2repo 'http://download.eclipse.org/releases/2020-03/202003181000'
    p2repo 'http://download.eclipse.org/sphinx/releases/0.11.x'
    install 'org.eclipse.emf.ecore'
    install 'org.eclipse.sphinx.emf'
  }
}
```

**Comment by dhakehurst** [comment]
you should definitely document this properly somewhere...its no obvious

**Comment by nedtwigg** [comment]
Thanks for the example above, that will be very helpful to others. I have deleted our discussion so that the example is easier to find.
