### ISSUE TITLE
How can I get the path to the workspace?

### ISSUE THREAD

**Issue by dscowan** [diffplug/goomph#22]
I need to overlay some non prefs files into the .metadata/.plugins/(etc) folders but do not know how to get the path to the user directory based workspace folder.  Also when would be the best time to hook into overlaying these folders?  ideSetupWorkspace.finalize?

**Comment by nedtwigg** [comment]
The workspace is setup [here](https://github.com/diffplug/goomph/blob/98c7a29000b330700ee3c32eab56486a3e49ecd4/src/main/java/com/diffplug/gradle/oomph/OomphIdeExtension.java#L347-L363).

The workspace directory can be obtained with `OomphIdeExtension::getWorkspaceDir()`, which calls out to the [WorkspaceRegistry](https://github.com/diffplug/goomph/blob/98c7a29000b330700ee3c32eab56486a3e49ecd4/src/main/java/com/diffplug/gradle/oomph/WorkspaceRegistry.java).  I hate that we need such a complicated setup, but we do, as described in the javadoc for the workspace registry.

What do your prefs files look like?  Ideally we'd add an api similar to `OomphIdeExtension::workspaceProp` which could accomodate them.

**Comment by dscowan** [comment]
I am trying to add favorites for launchers which end up as launchConfigurationHistory.xml under .metadata/.plugins/org.eclipse.debug.ui
The xml has launch history.

**Comment by nedtwigg** [comment]
Can you paste a sample file of what it looks like?  I can think of two apis:

```gradle
workspaceFile('destinationPath', 'sourcePath')
workspaceXml('destinationPath', 'rootXmlElement', {
    key 'value'
    node {
        otherKey 'otherValue'
    }
})
```

I think `workspaceFile` is easier, but maybe harder to customize for user paths, etc.  `workspaceXml` is pretty verbose, but pretty flexible too.

**Comment by dscowan** [comment]
This is the launchConfigurationHistory.xml.  I think both would be useful.

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchHistory>
<launchGroup id="com.mountainminds.eclemma.ui.launchGroup.coverage">
<mruHistory>
<launch memento="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#13;&#10;&lt;launchConfiguration local=&quot;false&quot; path=&quot;/test-app/testApp.launch&quot;/&gt;&#13;&#10;"/>
</mruHistory>
<favorites>
<launch memento="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#13;&#10;&lt;launchConfiguration local=&quot;false&quot; path=&quot;/test-app/testApp.launch&quot;/&gt;&#13;&#10;"/>
</favorites>
</launchGroup>
<launchGroup id="org.eclipse.debug.ui.launchGroup.debug">
<mruHistory>
<launch memento="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#13;&#10;&lt;launchConfiguration local=&quot;false&quot; path=&quot;/test-app/testApp.launch&quot;/&gt;&#13;&#10;"/>
</mruHistory>
<favorites>
<launch memento="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#13;&#10;&lt;launchConfiguration local=&quot;false&quot; path=&quot;/test-app/testApp.launch&quot;/&gt;&#13;&#10;"/>
</favorites>
</launchGroup>
<launchGroup id="org.eclipse.debug.ui.launchGroup.profile">
<mruHistory/>
<favorites/>
</launchGroup>
<launchGroup id="org.eclipse.ui.externaltools.launchGroup">
<mruHistory/>
<favorites/>
</launchGroup>
<launchGroup id="org.eclipse.debug.ui.launchGroup.run">
<mruHistory>
<launch memento="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#13;&#10;&lt;launchConfiguration local=&quot;false&quot; path=&quot;/test-app/testApp.launch&quot;/&gt;&#13;&#10;"/>
</mruHistory>
<favorites>
<launch memento="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;&#13;&#10;&lt;launchConfiguration local=&quot;false&quot; path=&quot;/test-app/testApp.launch&quot;/&gt;&#13;&#10;"/>
</favorites>
</launchGroup>
</launchHistory>
`

**Comment by nedtwigg** [comment]
I implemented the stuff required.  Can you test that 3.6.0-SNAPSHOT does what you need?

```gradle
    workspaceFile('destinationPath', 'sourcePath')    // copies some file into the workspace
    workspaceXml('destinationPath', { xmlProvider ->
        // can ONLY be called after a call to workspaceFile
        // workspaceXml can modify existing xml, but can't create it from scratch
        // see examples for other gradle xml manipulation, e.g.
        //     https://docs.gradle.org/current/userguide/publishing_maven.html#sec:modifying_the_generated_pom
        //     http://mrhaki.blogspot.com/2012/09/gradle-goodness-customize-idea-project.html
    })
```

**Comment by dscowan** [comment]
This works well, Thanks
