### ISSUE TITLE
Pass proxy settings from GRADLE_OPTS to P2 director.

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/goomph#3]
*Migrated from [gradle_and_eclipse_rcp#5](https://github.com/diffplug/gradle_and_eclipse_rcp/issues/5).*

Goomph works by downloading a minimal (~10MB) eclipse installation, and then using that installation to run headless applications that do the work.  We need to read proxy settings from GRADLE_OPTS, and then pass them to these headless apps.

[Here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=382875) is the bug in Eclipse bugtracker for proxy support in headless apps, summarized below:

Make a file `proxies.ini` with content like this:

```
org.eclipse.core.net/proxyData/HTTP/host=someproxy.ericsson.se
org.eclipse.core.net/proxyData/HTTPS/host=someproxy.ericsson.se
org.eclipse.core.net/proxyData/HTTPS/hasAuth=false
org.eclipse.core.net/proxyData/HTTP/port=8080
org.eclipse.core.net/proxyData/HTTPS/port=8080
org.eclipse.core.net/org.eclipse.core.net.hasMigrated=true
org.eclipse.core.net/nonProxiedHosts=*.ericsson.com|127.0.0.1
org.eclipse.core.net/systemProxiesEnabled=false
org.eclipse.core.net/proxyData/HTTP/hasAuth=false 
```

And pass it to command line with `-plugincustomization proxies.ini`.

The problem is that this mechanism doesn't work for proxies that need a password field. There is another mechanism (mentioned in the eclipse bug), but it's a little tricky.

If anybody needs proxy support, reply with the answers to this question, I can do the rest:

1. What GRADLE_OPTS parameters do you set
2. What would your `proxies.ini` file look like

Dummy values would be fine, of course, but I need a testcase for the parsing logic.  If you can supply 1 & 2 above, I can do the rest.  If your proxy needs a password, you'll have to do a manual step in the GUI (at least for now.  Eclipse bug above is working on a fully headless solution).

**Comment by edeandrea** [comment]
So my apologies for letting this lapse. I've actually switched jobs and am no longer working at the company I was. I'm just getting settled in here so not sure I'll be able to help out with this for now unfortunately. Just didn't want you to think I had abandoned it.

**Comment by nedtwigg** [comment]
No worries, thanks for getting in touch.  It's a useful issue for anyone else who might bump into this as well.

**Comment by dscowan** [comment]
I'm having this same issue.  For gradle proxy settings I usually use this

JAVA_OPTS=-Dhttp.proxyHost=proxyhostname -Dhttp.proxyPort=proxyport

**Comment by nedtwigg** [comment]
@dscowan, have you tried the `proxies.ini` workaround above?  If you copy-paste the goomph part of your build.gradle, I can show you how to modify it to point to the `proxies.ini`.

**Comment by dscowan** [comment]
@nedtwigg I did not know you could modify the proxies.ini from the goomp task.  Here it is

`oomphIde {
    repoEclipseLatest()
    jdt {}

    repo 'http://download.eclipse.org/buildship/updates/e46/releases/1.0'
    repo 'http://download.eclipse.org/mpc/neon/'
    repo 'https://sonarsource.bintray.com/SonarLint-for-Eclipse/releases/2.2.1'
    repo 'http://download.eclipse.org/egit/updates/'
    repo 'http://download.eclipse.org/mylyn/releases/latest'
    repo 'http://dadacoalition.org/yedit'    

    //feature 'org.eclipse.epp.mpc'
    feature 'org.eclipse.buildship'
    feature 'org.eclipse.egit'
    feature 'org.eclipse.egit.mylyn'
    feature 'org.eclipse.jgit'
    feature 'org.sonarlint.eclipse.feature'
    feature 'org.sonarlint.eclipse.jdt.feature'
    feature 'org.dadacoalition.yedit.feature'
    

    eclipseIni {
        vmargs('-Xmx2g')    // IDE can have up to 2 gigs of RAM
    }
    style {
        niceText()		// nice fonts and visible whitespace
    }
    addAllProjects()
}`

**Comment by nedtwigg** [comment]
@dscowan It's not an easy process yet, but we might be able to make it one.  You'll need the latest 3.3.0-SNAPSHOT version ([info](https://github.com/diffplug/goomph/blob/master/CONTRIBUTING.md)).

add this to your `oomphIde` block:

```gradle
oomphIde {
    ...

    p2director {
        addArg('plugincustomization', '<path to proxies.ini>')
    }
}
```

And you'll have to make the "proxies.ini" yourself, see the format above.  If this works, then we could add a feature to detect "-Dhttp.proxyHost=proxyhostname -Dhttp.proxyPort=proxyport" and then do this automatically.  But before putting in that much effort, I wanna make sure the workaround works, and see what the `proxies.ini` needs to include.

**Comment by dscowan** [comment]
@nedtwigg This worked perfectly.  Thanks!

**Comment by nedtwigg** [comment]
@dscowan do you mind posting what your proxies.ini looks like?  Not the real passwords, just the format of it.  I'd like for Goomph to do this automatically, at least to support `-Dhttp.proxyHost=proxyhostname -Dhttp.proxyPort=proxyport`.

**Comment by dscowan** [comment]
@nedtwigg I used what is above replacing the host fields and port field

`org.eclipse.core.net/proxyData/HTTP/host=someproxy.ericsson.se
org.eclipse.core.net/proxyData/HTTPS/host=someproxy.ericsson.se
org.eclipse.core.net/proxyData/HTTPS/hasAuth=false
org.eclipse.core.net/proxyData/HTTP/port=8080
org.eclipse.core.net/proxyData/HTTPS/port=8080
org.eclipse.core.net/org.eclipse.core.net.hasMigrated=true
org.eclipse.core.net/nonProxiedHosts=*.ericsson.com|127.0.0.1
org.eclipse.core.net/systemProxiesEnabled=false
org.eclipse.core.net/proxyData/HTTP/hasAuth=false `

**Comment by nedtwigg** [comment]
Gotcha.  It looks complicated enough, and I'm ignorant enough of proxies that I'm hesitant to make this automatic.  Just released `3.3.0`, you don't need a snapshot anymore.  I'm marking this as "implemented", since we now have a workaround.  If people are interested in an easier workaround, I'm going to track that as a separate issue [#12](https://github.com/diffplug/goomph/issues/12).

**Comment by dscowan** [comment]
@nedtwigg I think this workaround is sufficient for most cases.  Thanks for the quick responses.

**Comment by hacki11** [comment]
How do i pass proxy parameter into PdeBuildTask for downloading eclipse?

**Comment by nedtwigg** [comment]
I'm guessing that your answer is #25.

**Comment by nedtwigg** [comment]
Strongly recommend migrating to `dev.equo.ide` or `dev.equo.p2deps`. I'm not positive this particular issue is solved there, but even if it isn't it will be a lot easier to fix under the EquoIDE approach rather than the Goomph approach. https://github.com/equodev/equo-ide/tree/main/plugin-gradle
