### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by QingMings** [diffplug/goomph#32]
I'm sorry ,i read the Readme.md file , 
and  i clone this repo in my eclipse 
i don't know how to use it to create eclipse-plugin project .
I also try `gradlew eclipse ` ,and it build successful, but I can't find it .
Can you provide some documentation and demonstrate it step by step?
Feelings including Tycho, is a scarce document, maybe they did a lot of things, but it is very difficult for a novice.

**Comment by nedtwigg** [comment]
I'd recommend starting here: https://github.com/diffplug/gradle-and-eclipse-rcp
