### ISSUE TITLE
How can I stop goomph from downloading p2 bootstrap from bintry?

### ISSUE THREAD

**Issue by beginnerbegin** [diffplug/goomph#36]
I downloaded the goomph plugin and started to build eclipse plugins. Apparently the goomph is trying to download goomph-p2-bootstrap from bintray but my organization doesn't allow that. How do I remove bootstrap dependency?

The error message: server returned HTTP response code: 403 for URL: http://do.bintray.com/diffplug/opensource/com/diffplug/Gradle/goomp-p2-bootstrap/4.5.2/goomp-p2-bootstrap
Zip

**Comment by nedtwigg** [comment]
The bootstrapper is required, but you can copy it to a [local URL behind your firewall](https://github.com/diffplug/goomph/issues/25#issuecomment-266641562).

**Comment by beginnerbegin** [comment]
Thank you. Just making sure, if it's available in local, the goomph will not try to download, right?

**Comment by nedtwigg** [comment]
Goomph will still download, but it will download from your local URL, not a remote URL.  Goomph needs the the bootstrapper - it doesn't work without it.

**Comment by nedtwigg** [comment]
Feel free to reopen if you have further issues.
