### ISSUE TITLE
Proxy Settings for p2AsMaven 

### ISSUE THREAD

**Issue by I-Xenophon-I** [diffplug/goomph#37]
I am new to Gradle and I tried to pass the proxy settings as described in the documentation of the class com.diffplug.gradle.p2.AsMavenPlugin via:

```
p2AsMaven {
    group 'myGroup', {
        ...
        p2ant {
            addArg('plugincustomization', 'proxies.ini')
        }
    }
}
```

However, if I run the build I get the error message:

> Could not find method addArg() for arguments [plugincustomization, proxies.ini] on object of type com.diffplug.gradle.p2.AsMavenGroup.

**Comment by nedtwigg** [comment]
Maybe try

```gradle
p2ant ({
    addArg ....
})
```

If that doesn't work, can you link to your real build.gradle?

**Comment by I-Xenophon-I** [comment]
My minimalist build.gradle file:

```
buildscript {
   repositories {
      maven {
         url 'https://plugins.gradle.org/m2/'
      }
   }
   
   dependencies {
      classpath "com.diffplug.gradle:goomph:+"
   }
}

apply plugin: 'com.diffplug.gradle.p2.asmaven'

p2AsMaven {
   group 'eclipse-deps', {
      repoEclipse '4.6.0'
      
      p2ant {
         addArg('plugincustomization', 'proxies.ini')
      }
   }
}
```

**Comment by nedtwigg** [comment]
What gradle version?

**Comment by I-Xenophon-I** [comment]
Version 4.0.2

**Comment by nedtwigg** [comment]
Weird.  This fixed it:

```gradle
p2ant {
    it.addArg( .....
}
```

Dunno why we need the `it`, but it works.  I'll update the docs.

**Comment by I-Xenophon-I** [comment]
Thanks for your help!
