### ISSUE TITLE
Cannot customize jar anymore

### ISSUE THREAD

**Issue by drfreaky** [diffplug/goomph#38]
I have to put some extra files in my jar file at a specific location (copy files from srcDir to DstDir in jar). I do something like this in my Gradle file
```
jar {
    from ('srcDir') {
        into('DstDir')
    }
}
```
If I add `apply plugin: "com.diffplug.gradle.osgi.bndmanifest"` to my Gradle file, the files won't copied into the jar anymore... ;(

**Comment by nedtwigg** [comment]
Bummer!  If you'd like to take a hack at fixing it, [the code involved](https://github.com/diffplug/goomph/blob/master/src/main/java/com/diffplug/gradle/osgi/BndManifestPlugin.java) is pretty small, and [the dev process](https://github.com/diffplug/goomph/blob/master/CONTRIBUTING.md) is pretty simple.  This is a bug worth fixing, but it won't make it to the top of my todo-list.  Happy to merge any PRs.

**Comment by nedtwigg** [comment]
Fixed in `3.16.0`.
