### ISSUE TITLE
buildproperties plugin hangs due copy module-root into build-dir without build.properties

### ISSUE THREAD

**Issue by hacki11** [diffplug/goomph#39]
Having activated `apply plugin: 'com.diffplug.gradle.eclipse.buildproperties'` without having a build.properties copies everything from module root into build/resources/main/ in task processResources.

After the first build call the directory structure having massive amounts of recursive content of the build output itself. The next build call will never end because of recursively copying everything into.

I debugged the plugin to get the difference in the copy job with and without the build.properties file but my knowledge with copy actions is too basic to get the difference.

**Comment by nedtwigg** [comment]
When there's not a properties file, binIncludes is empty, which means [this loop](https://github.com/diffplug/goomph/blob/e8e6f57323a8f0f62da701f809805427378d9865/src/main/java/com/diffplug/gradle/eclipse/BuildPropertiesPlugin.java#L80-L88) never runs.  The plugin currently warns if there's no `build.properties`, but it should probably not do anything at all rather than warn...

**Comment by nedtwigg** [comment]
In 3.9.0-SNAPSHOT, the plugin will error if there is no `build.properties`, rather than recursively copy stuff.  Thanks for the fix!  Tentative plan is to roll this into a release this when Oxygen.2 comes out 12/20.

**Comment by hacki11** [comment]
personally i would prefer a less invasive plugin which is fail-operational.
what i mean is, the plugin should not error and stop the build process if it can not be applied. simple example would be a the java plugin which can not find any java sources - will it fail?

**Comment by nedtwigg** [comment]
The java plugin has infrastructure that other plugins add on to.  What's the usecase for applying `com.diffplug.gradle.eclipse.buildproperties` to a plugin without a `build.properties` file?  What should the behavior be - to produce an empty jar file?

**Comment by hacki11** [comment]
i am generating an eclipse .classpath and .project file for all my plugins. if there is no entry, i expect it is generated like no buildproperties plugin is activated (setting src/main/java, src/main/resources, ...). As soon as i have specific folder configuration (like adding specific resource or source paths), for which i must create a build.properties i do not need to specifically add the plugin. It would just work out of the box.

**Comment by nedtwigg** [comment]
How about:

```gradle
if (file('build.properties').exists()) {
    apply plugin: 'com.diffplug.gradle.eclipse.buildproperties'
}
```

**Comment by hacki11** [comment]
yes, this will work for me! thank you!
(i just switched from maven to gradle - iam not too familiar with such a flexibility gradle provides)
thanks for your work too, we are porting build system of our ~40 eclipse rcp plugins right now. its looks very promising

**Comment by nedtwigg** [comment]
Can we list your company as a user [in this list](https://github.com/diffplug/goomph/blob/master/README.md#building-osgi-bundles-eclipse-plugins-and-rcp-applications)?  More users makes it more likely for bugs to get fixed and features to get added, and it helps people to adopt when they know that real commercial entities are using it.
