### ISSUE TITLE
Question about FeaturesAndPublisher and goomph capacities to generate p2 site ?

### ISSUE THREAD

**Issue by reyman** [diffplug/goomph#42]
Hi, i finally found a way to create an eclipse plugin which works, i try your way and bnd-platform way to do that.

The `bnd-platform` way works well, i have something like that : 

apply plugin: 'org.standardout.bnd-platform'

```
platform {

    eclipseMirror.linux.gtk.x86_64 = 'http://ftp.fau.de/eclipse/technology/epp/downloads/release/mars/R/eclipse-java-mars-R-linux-gtk-x86_64.tar.gz'
    determineImportVersions = true
    useBndHashQualifiers = false
    fetchSources = false
    importVersionStrategy = MAJOR

    feature(id: 'genstar.plugin', name: 'genstar.plugin', version: '1.0.0') {

        //plugin 'genstar.plugin.bundle-all:genstar.plugin.bundle-all:1.0.0'
        bundle file('../genstar.plugin.bundle-all/build/libs/genstar.plugin.bundle-all.jar')

    }
}
```

This code generate both a feature and a plugins folder, and it works with eclipse plugin system.

With goomph way, the `FeaturesAndPublisher` seems to generate only a plugin folder. The site generated is not visible by eclipse plugin system if you don't create a features folder with corresponding information. Is there a way to create this features which includes bundle declaration into goomph ? I'm really interested by this features because goomph is more updated than bnd-platform.

Here my code to generate the plugins folder of p2 site with `FeaturesAndPublisher` :  

```
import com.diffplug.gradle.p2.FeaturesAndBundlesPublisher;
import com.diffplug.gradle.eclipserunner.NativeRunner;

task p2site(dependsOn: bundles){
    doLast {
        println 'bundle and deploy'

        FeaturesAndBundlesPublisher p2Publisher = new FeaturesAndBundlesPublisher();
        File source = new File("/home/reyman/Projets/genstar-gama-plugin/genstar.plugin.platform/build/")
        File outputFolder = new File("/home/reyman/Projets/genstar-gama-plugin/genstar.plugin.platform/p2site/")
        outputFolder.mkdir()

        File eclipseFolderExec = new File("/home/reyman/Projets/genstar-gama-plugin/genstar.plugin.platform/build/eclipse-downloads/eclipse/eclipse")
        p2Publisher.source(source)
        p2Publisher.compress()
        p2Publisher.addArg("nosplash", "")
        p2Publisher.addArg("debug", "")
        p2Publisher.artifactRepository(outputFolder)
        p2Publisher.metadataRepository(outputFolder)
        p2Publisher.publishArtifacts()

        p2Publisher.runUsing(new NativeRunner(eclipseFolderExec))
    }
}
```

Thanks a lot for your help,
SR

**Comment by nedtwigg** [comment]
If bnd-platform does what you need, I would use that!  I use bnd-platform in all my eclipse builds, and it's featured heavily in the goomph [demo app](https://github.com/diffplug/gradle-and-eclipse-rcp/blob/master/target.maven/build.gradle).  If you need an updated bnd version, I bet Simon would merge and release a PR with an updated bnd.

Goomph is all just thin wrappers around Eclipse.  If it's not doing what you need, the answer is in the eclipse docs, which are linked to from the Goomph javadoc.
