### ISSUE TITLE
Adding "append" Feature to p2asmaven plugin

### ISSUE THREAD

**Issue by hacki11** [diffplug/goomph#43]
On a dependency change in the p2asmaven plugin config the whole already downloaded repository is deleted and redownloaded.

The p2.mirror ant tasks supports an "append" feature where one can set true for keeping the downloaded dependencies and just adding the new. Setting this to false will remove all deps from the target repository beforehand. During integration of the plugin, it is often needed to add dependencies incrementally and a whole rebuild is needed (up to 40 minutes).

To add this feature i think the following would have to be changed:

Instead of <destination> it should be called <repository>
https://github.com/diffplug/goomph/blob/a2dbf4c2d03559649fc776694dc523944d8010a1/src/main/java/com/diffplug/gradle/p2/P2Model.java#L249
https://wiki.eclipse.org/Equinox/p2/Ant_Tasks#Simple_Examples

Instead of deleting the directory:
https://github.com/diffplug/goomph/blob/a2dbf4c2d03559649fc776694dc523944d8010a1/src/main/java/com/diffplug/gradle/p2/AsMavenGroupImpl.java#L71

a method "append(boolean)" can be introduced inside P2Model. If set, the ant task will clean the target dir.

This will improve the time of getting an application compiled in eclipse against all the needed dependencies without the redownload hassle (i installed a nexus p2 mirror but still costs time)

are you interested in a pull request regarding this feature?

**Comment by hacki11** [comment]
Yes, i would also recommend to have append = false as default to avoid changing current behavior. Append would also reference better to the backed p2.mirror feature.

**Comment by nedtwigg** [comment]
Shipped in `3.9.0`.
