### ISSUE TITLE
com.diffplug.gradle.swt should point users to the official maven coordinates for Eclipse artifacts

### ISSUE THREAD

**Issue by cobexer** [diffplug/goomph#47]
Since some time already there are official Maven coordinates available for some eclipse artifacts and thus this plugin should point users towards the official maven coordinates instead of using the p2 repositories.

An automatic conversion is probably hard since the eclipse version and the SWT version aren't equal but pointing more users to the maven coordinates would increase the pressure on the eclipse projects to improve their maven artifacts.

Some relevant eclipse bug reports: https://bugs.eclipse.org/bugs/show_bug.cgi?id=484004 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=510072

Some of the official coordinates:
https://search.maven.org/#search|ga|1|g%3Aorg.eclipse.platform
https://search.maven.org/#search|ga|1|g%3Aorg.eclipse.jdt
https://search.maven.org/#search|ga|1|g%3Aorg.eclipse.pde

**Comment by nedtwigg** [comment]
I'm hoping to move as much of my work off of p2 and onto the mavenCentral artifacts as possible!  This is what I have in mind:

```gradle
eclipseDepsInMaven {
    eclipse = '4.7.0'   // the eclipse release which is present in maven
    compile 'org.eclipse.jdt:org.eclipse.jdt'  // the maven artifact
    compile 'org.eclipse.platform:org.eclipse.swt'
    // the plugin will add the specific version of the specific dependencies,
    // by downloading p2 metadata from the specific eclipse release
}
```

It's not at the top of my list, and won't be for at least a few months.  Happy to take a PR for it.

**Comment by nedtwigg** [comment]
I've got something mostly done here.  I'll polish and upload in a week or two.

**Comment by nedtwigg** [comment]
Implemented.
