### ISSUE TITLE
Feature: PdeBuildTask should recognize 'includeLaunchers' property

### ISSUE THREAD

**Issue by hacki11** [diffplug/goomph#56]
`<product name="Product" uid="ProductUid" id="fully.qualified.name.Product" useFeatures="false" includeLaunchers="false">`

`ProductFileUtil` should find includeLaunchers to be used in the build properties.

Workaround, setting props as redundant:
`props['includeLaunchers'] = 'false'`

**Comment by nedtwigg** [comment]
`<product name="Product"...` is an excerpt from a product file?  Regardless, sounds like a good improvement to me 👍

**Comment by hacki11** [comment]
correct, this is a product file eclipse generates for the pde exports.
feature added in #58
