### ISSUE TITLE
simple eclipse plugin sample

### ISSUE THREAD

**Issue by mxab** [diffplug/goomph#6]
Hi,
Are there any docs or code samples how to setup and build a simple eclipse plugin project, I tried to look through `gradle_and_eclipse_rcp` code but it there is a bit to much to comprehend.

**Comment by nedtwigg** [comment]
I started an example here:

https://github.com/diffplug/goomph-eclipse-plugin

The example downloads all the dependencies you need, and sets up an IDE with all the pieces you'll need.  It isn't a complete example, but it's a start.  If you need more help, just let me know.
