### ISSUE TITLE
gradle.p2.asmaven for xtext and xcore libs

### ISSUE THREAD

**Issue by Ealrann** [diffplug/goomph#63]
Hello,

I open an issue, but this is just to ask a question, I don't feel I spot a bug actually.

I need to use some p2 libraries with my java project. I'm able to get the EMF ones with p2asmaven, but xtext and xcore still can't be found :

> 
> BUILD FAILED
> /tmp/goomph-ant-build4488776739356892255.xml:3: Unable to find: Installable Unit [ id=org.eclipse.xtext.xbase.lib ]

Here my buid.gradle:

> plugins {
>     id 'org.gradle.java.experimental-jigsaw'
>     id 'com.diffplug.gradle.p2.asmaven'
> }
> 
> p2AsMaven {
>     // the maven group they shall have
>     group 'eclipse-deps', {
>    
>         // the repositories and artifacts to download
>         repoEclipse '4.7.2'
> 
>         iu 'org.eclipse.emf.ecore'
>         iu 'org.eclipse.emf.common'
>         iu 'org.eclipse.emf.ecore.xmi'
>         iu 'org.eclipse.xtext.xbase.lib'
>         iu 'org.eclipse.emf.ecore.xcore.lib'
>     }
> }
> 

I'm using 'com.diffplug.gradle.p2.asmaven' version '3.13.0'.

Thank you for any possible help :).

**Comment by nedtwigg** [comment]
`repoEclipse '4.7.2'` is the repo for the Eclipse IDE components, but it doesn't have all of emf and xtext.  You'll need to add the p2 repository for those features.

[This chat log](https://gitter.im/diffplug/goomph?at=5a98fdff8f1c77ef3a724683) might be helpful.

**Comment by Ealrann** [comment]
Thank you! I now have something working.
Here the configuration:

```
p2AsMaven {
	group 'eclipse-deps', {

		repoEclipse '4.7.3'
		
		// Xcore repo
		repo("http://download.eclipse.org/modeling/emf/emf/builds/milestone/latest")
		
		// Xtext
		repo("http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest")
		
		// Just for a recent version of guava
		repo("http://download.eclipse.org/linuxtools/update-mylyn")

		iu 'org.eclipse.emf.ecore'
		iu 'org.eclipse.emf.common'
		iu 'org.eclipse.emf.ecore.xmi'
		iu 'org.eclipse.xtext.xbase.lib'
		iu 'org.eclipse.emf.ecore.xcore.lib'
    }
}
```
