### ISSUE TITLE
How can I add a depencency to a feature in a subproject?

### ISSUE THREAD

**Issue by MarceloRuiz** [diffplug/goomph#64]
Hi,
I configured goomph to download content from a p2 repository and it did it with no problem. I configured a subproject that has the product definition with a reference to an existing feature (actually downloaded into the p2/eclipse-deps/features folder) but eclipse cannot be resolved. I know I need to set it in the dependencies section of the build.gradle file of the subproject. How can I achieve that? 
Thanks!

**Comment by MarceloRuiz** [comment]
Thanks. So, if I understand correctly, the product definition should be changed from features to plugins and then add the plugins as dependencies in its definition on top of adding the runtime plugin dependencies on the project's build.gradle?
Lastly, the p2 repository I am using has all the dependencies necessary to run an e(fx)clipse project, but when I launch the project (from the product file), I get a `java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter`
If e(fx)clipse launches the project in a different way, is there a way to configure or customize this?
Thanks

**Comment by nedtwigg** [comment]
I don't know anything about e(fx)clipse, but from that error message, it seems likely that you're missing whichever dependency contains `org.eclipse.core.runtime.adaptor.EclipseStarter`.

I only have experience with plugin-based builds, though I think it is possible to use a feature-based build.  Problem is, you'll have to do all the "feature" work yourself - gradle has no conceptual analogue to feature, so it would all be manual.

**Comment by MarceloRuiz** [comment]
Yes, I understand that. So is my assumption of having the plugin dependencies basically duplicated in the product file and gradle.build correct?

**Comment by nedtwigg** [comment]
Feel free to reopen if you'd like to discuss further.
