### ISSUE TITLE
EquinoxLaunch cannot handle EXIT_ASYNC_RESULT

### ISSUE THREAD

**Issue by frankbenoit** [diffplug/goomph#65]
Hello Ned,

i used the EquinoxLaunch and it worked well.
Now i changed my application.
Before the change, all actions where running in the IApplication#start method and returned the exit code directly.
Now my application creates a thread to run the work, and IApplication#start returns IApplicationContext.EXIT_ASYNC_RESULT (this is not an instance of Integer, just a raw Object).  
Later the thread calls ctx.setResult(0, this); and the IApplication#stop method waits for the thread to finish.  
From within Eclipse this works.
Now in gradle with EquinoxLaunch I get this output:
> Unexpected return=0, was: java.lang.Object@59309333

Without knowing the EquinoxLaunch, i guess that the EXIT_ASYNC_RESULT is just passed forward.
But in this case, that the return is not an Integer instance, the stop method should be waited for and the return code can be retrieved in the property "eclipse.exitcode"

**Comment by nedtwigg** [comment]
I think the exception was thrown here:

https://github.com/diffplug/goomph/blob/3278935084cfd6e6372ee4f688568b774ca0fdfd/src/main/java/com/diffplug/gradle/eclipserunner/EquinoxLauncher.java#L192-L193

If there's additional functionality you require, we're happy to merge a PR for them, but it's not on our roadmap.
