### ISSUE TITLE
Is it possible to specify multiple p2 repositories?

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/goomph#7]
*Excerpted from a private conversation with a Goomph user*

With the p2AsMaven plugin, is it possible to specify both the eclipse 4.5.2 p2 repo and our own p2 repo and pull the plugin jars down from both into the build dir?

**Comment by nedtwigg** [comment]
Yup.  The [javadoc](https://diffplug.github.io/goomph/javadoc/3.1.0/com/diffplug/gradle/p2/AsMavenPlugin.html) has more details, but here's the gist:

```groovy
p2AsMaven {
    group 'mavenGroup1', {
        repo 'http://p2url'
        iu 'foo.someiu'
    }
    group 'mavenGroup2', {
        repo 'http://someOtherP2Url'
        iu 'foo.someotheriu'
    }
}
```

In most examples, it says `repoEclipse '4.5.2'` or something like that, instead of just `repo`.  That's just a shortcut so you don't have to type out the full eclipse p2 url for each version.

**Comment by bensullivan** [comment]
Thanks very much Ned.  I've jumped onto the gitter channel to help ramp up my understanding of this plugin.
