### ISSUE TITLE
Missing OSGi bundles in generated config.ini

### ISSUE THREAD

**Issue by Tobbe0430** [diffplug/goomph#70]
I have a question regarding the configuration folder generated when trying to build a RCP with your plugin.
The question is how the bundle information get into the config.ini-file. For instance, org.eclipse.core.runtime seems to be missing from the osgi.bundles header which causes an error in the application complaining bout how core.runtime should be up and started.

What's deciding how config.ini is generated?

EDIT: I should add that I have a configurations block in my .product file like this:

```
<configurations>
      <plugin id="org.eclipse.core.runtime" autoStart="true" startLevel="4" />
      <plugin id="org.eclipse.equinox.simpleconfigurator" autoStart="true" startLevel="1" />
</configurations>
```

**Comment by nedtwigg** [comment]
The config.ini is built by shelling out to Eclipse PDE

https://github.com/diffplug/goomph/blob/af5fc92d98b1e622c44c423cdf3bf5c984562b7b/src/main/java/com/diffplug/gradle/pde/PdeInstallation.java#L142-L148

So the docs you're looking for are probably here: http://help.eclipse.org/oxygen/nav/4_2

**Comment by Tobbe0430** [comment]
Thank you. I managed to solve it by moving the plugins from the <configurations> block to the <plugins> block instead.
