### ISSUE TITLE
"Could not retrieve POM" spam when running assemble.all

### ISSUE THREAD

**Issue by Tobbe0430** [diffplug/goomph#71]
Whenever I execute "./gradlew assemble.all", the task :bundles will be followed by a long list of "Could not retrieve POM" followed by a plugin name. The output is the same when I run the gradle-and-eclipse-rcp example project.

The problem is that it takes quite a time for my project to go through all those plugins since I have a few more than the example. Do you have an idea of how this could be solved in a good way?

**Comment by nedtwigg** [comment]
The :bundles project doesn't have goomph applied at all.  That's the [bnd-platform](https://github.com/stempler/bnd-platform) project.  It's completely independent to goomph, but they work very well together.  You'll have to ask there.
