### ISSUE TITLE
p2.inf 

### ISSUE THREAD

**Issue by Tobbe0430** [diffplug/goomph#73]
Hi,

I have a question regarding providing a p2.inf file with information to the pde build. Is there a convenient  way of doing this with goomph? It is very possible that I've missed out something in the documentation.

**Comment by nedtwigg** [comment]
Whatever way there is for providing it to a command-line build (ant or shell script), I'm sure Goomph can do it too.  We just shell out to the eclipse built-in commands.  If you provide a link to the eclipse docs, then I can help you goomph that part.

**Comment by nedtwigg** [comment]
[This](https://wiki.eclipse.org/Equinox/p2/Customizing_Metadata) describes where you should place them.  You might need to add the `p2.inf` to the `build.properties` of the bundles you're working with.  [These docs](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_p2_configuringproducts.htm) are also pertinent.

**Comment by Tobbe0430** [comment]
Thank you very much for your input.

I've followed the steps in the documentation but the settings specified in p2.inf does not seem to apply to the installable unit. Do you know if it is possible to see if the file is actually used in the build?

**Comment by nedtwigg** [comment]
Maybe by combing over the logs?  I've had trouble with p2 touchpoints around unix permissions, it seems they were documented but never actually implemented.

**Comment by Tobbe0430** [comment]
Solved it with a workaround! Thanks for the help though. :+1:

**Comment by nedtwigg** [comment]
Can you describe the workaround in case others have the same problem in the future?

**Comment by Tobbe0430** [comment]
I ended up not using p2.inf at all since it was ignored. Instead I configured the update site directly with the .pref file.
