### ISSUE TITLE
PdeBuildTask p2 repository

### ISSUE THREAD

**Issue by chrjo5** [diffplug/goomph#75]
Hi,

I'm trying to use PdeBuildTask in order to make a p2 repository. However, I'm struggling to find further information about how this could be done together with goomph. Is there perhaps any more information available that I have missed out on?

**Comment by nedtwigg** [comment]
- http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Fintro%2Fpde_overview.htm&anchor=build
