### ISSUE TITLE
Eclipse RCP and JUnit plug-in tests

### ISSUE THREAD

**Issue by chrjo5** [diffplug/goomph#77]
Hi!

I've built an Eclipse RCP application in gradle using Goomph and want to run some junit plug-in tests. Do you know if I have to do something else rather than using the normal gradle test task procedure with testCompile junit in order to get the tests to run properly? Right know there are issues with some of my tests since things like...:

`org.eclipse.core.resources.ResourcesPlugin.getWorkspace()`

...throws exceptions.

**Comment by nedtwigg** [comment]
Yep, you'll need your plug-in tests to run in an OSGi environment.  http://underlap.blogspot.com/2011/12/osgi-testing-with-gradle-and-pax-exam.html

**Comment by hacki11** [comment]
There is PDE support in the newest Snapshot of PAX
https://ops4j1.jira.com/wiki/plugins/servlet/mobile?contentId=167018497#content/view/167018497

This allows you starting up products easily. Using this for integration testing successfully. Unfortunately it is still not released yet.
