### ISSUE TITLE
Configuring proxy of eclipse created by task ide

### ISSUE THREAD

**Issue by moley** [diffplug/goomph#85]
Hi you, 

first of all I'd like to say, that goomph is a really really cool thing. I am preparing development setup for our company and this plugin eases this dramatically. 

But I am missing some features, which I could imagine to contribute by pull requests... 
The most important one is to configure the proxy in the ide which is created, which is not located in workspace, but in ide configuration itself (under build/oomph-ide.app/Contents/Eclipse/configuration/.settings/org.eclipse.core.net.prefs) 

I would add methods to OomphIdeExtension like : 
- instanceFile
- instanceProp
- instanceXml
like the ones for the workspace settings 
Is this feature interesting for you?
Do you have suggestions what I have to consider to get my pull request merged?

**Comment by nedtwigg** [comment]
This sounds great, I'd love to merge a PR for this feature if a new feature is needed.  No special hoops to jump through, but [`CONTRIBUTING.md`](https://github.com/diffplug/goomph/blob/master/CONTRIBUTING.md) has some helpful tips for getting a dev environment setup.

My only question is about the name "instance".  My understanding is that the "instance" folder and the "workspace" folder are the same thing.  [FAQ How do I specify where application data is stored?](https://wiki.eclipse.org/FAQ_How_do_I_specify_where_application_data_is_stored%3F)

The eclipse "important folders" are really confusing, I always [go to this](https://help.eclipse.org/neon/topic/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html#locations) to sort them out.

Maybe you want `install`?  or `config`?  I'm fine with adding whatever needs to be added, but I want to make sure we name it the right thing.

**Comment by moley** [comment]
Yes, your right, I mixed this up, so i think **install** would be the right one?

**Comment by moley** [comment]
Ok, I have finished my implementation, ready to contribute, but want to add some tests. As I did not find tests on the workspaceProp either. So my question: Is it a valid testcase for you to check afterwards if the property file with the properties exist at the expected location?

**Comment by moley** [comment]
Sorry, I think you misunderstood me.. I mean automatic unit tests, which simply configure a gradle with the ProjectBuilder api, run through the methods and check afterwards if the configured files exist without starting any eclipse, only plain file checks. I would add such a unit test, if this would be enough testing for this feature.

**Comment by nedtwigg** [comment]
Fantastic, that's definitely enough testing!

**Comment by moley** [comment]
Hi again @nedtwigg again, I think I found a bug while testing: 

in OomphIdeExtension, line 549 in method ideSetupWorkspace() that 
`OutputStream output = new BufferedOutputStream(new FileOutputStream(target))` must be removed, because it cleans the file, which should me modified afterwards.

Can you please double check?
Cheers
Markus

**Comment by nedtwigg** [comment]
Just FYI, if you open a file in GitHub and press `y`, it will change the URL to be an immutable link based on the object hash (doesn't go stale when master branch moves), and you can click near the line numbers to create an inline link as shown below.  I don't see what you're mentioning on line 549, but maybe you mean this?

https://github.com/diffplug/goomph/blob/3a5b49b64cc3136827ec0e3d2fc2743c8d80101b/src/main/java/com/diffplug/gradle/oomph/OomphIdeExtension.java#L514-L516

It sure looks like a bug to me, good catch!

**Comment by moley** [comment]
OK, good point, thanks for the info.... Yes, I mean this one.

**Comment by nedtwigg** [comment]
Sorry it took so long, but the xml problem you found has finally been fixed in `3.20.0`.  Hope I haven't been blocking you this whole time!

**Comment by nedtwigg** [comment]
EquoIDE is a new approach to the Goomph problem. It works way better and it's got a bigger team behind it. I'm not sure if it will pickup your proxy settings out of the box, but if you give it a try and have any issues, open an issue there and I'll be happy to help fix it.

https://github.com/equodev/equo-ide/tree/main/plugin-gradle
