### ISSUE TITLE
Proxy configuration in durian-io library. 

### ISSUE THREAD

**Issue by ralfgrossklaus** [diffplug/goomph#88]
Hi,

i was trying to build goomph behind a proxy. Several tests fail because of connection timeouts, although i configured proxy settings for gradle properly. My suggestion is that this is due to a bug in the durian-io library used by goomph:

`	private static final class UrlByteSource extends ByteSource {

		private final URL url;

		private UrlByteSource(URL url) {
			this.url = checkNotNull(url);
		}

		@Override
		public InputStream openStream() throws IOException {
			return url.openStream();
		}

		@Override
		public String toString() {
			return "Resources.asByteSource(" + url + ")";
		}
	}
`

The problem here is the `url.openStream()` which does not care about proxy settings. My suggestion would be to create a Proxy object here and call `url.openConnection(proxy).getInputStream()` 

Regards, Ralf

**Comment by nedtwigg** [comment]
I'm open to a PR on durian-io, but maybe this is a solution: https://github.com/gradle/gradle/issues/1233

**Comment by nedtwigg** [comment]
I recommend migrating to EquoIDE. https://github.com/equodev/equo-ide/tree/main/plugin-gradle
