### ISSUE TITLE
Specifying a custom P2 repository leads to non terminating/very long configuration time

### ISSUE THREAD

**Issue by niktekusho** [diffplug/goomph#96]
First of all, awesome project!

Now looking at the matter at hand: I have already searched for similar issues and found that #63 and #33 helped me configure the local project I am working on.

The basic configuration of the target.p2 is the following:

```groovy
import com.diffplug.gradle.pde.EclipseRelease

apply plugin: 'com.diffplug.gradle.p2.asmaven'

// plugin configuration
p2AsMaven {
    // bundles array (plugin and/or feature)
    def requiredBundles = [
		'org.eclipse.core.commands',
		'org.eclipse.core.resources',
		'org.eclipse.core.runtime',
		'org.eclipse.ui',
		'org.eclipse.ui.ide',
		'org.eclipse.jface',
		'org.eclipse.swt',
		//"org.eclipse.swt.${com.diffplug.common.swt.os.SwtPlatform.getNative()}",
		'org.eclipse.equinox.registry',
		'org.eclipse.equinox.common',
		'org.eclipse.osgi',
		'org.eclipse.core.jobs',
		'org.eclipse.ui.workbench',
		'org.eclipse.jdt.core',
		'org.eclipse.jdt.ui',
		'org.eclipse.text'
    ]

    // maven/gradle group
    group 'eclipse-deps', {
    	repoEclipse '4.9.0'
        // reduce the number of plugins downloaded
        slicingOption 'latestVersionOnly', 'true'
        requiredBundles.each {
            // iu = installable unit
            iu "${it}"
            // iu "${it}.sources"
        }
        append true
    }
}
```

This configuration leads to successful builds.

I would love to have the eclipse p2 repository on a nearer source so that CI builds could be faster (I have already thought of a workaround for that).

With this in mind I tried to change the source of the p2 repository by changing the maven/gradle group configuration to:

```groovy
    // maven/gradle group
    group 'eclipse-deps', {
        repo "file://D:/p2-eclipse/" // <-- local directory containing the p2 from https://download.eclipse.org/eclipse/updates/4.9/R-4.9-201809060745/
    	// repoEclipse '4.9.0'
        // reduce the number of plugins downloaded
        slicingOption 'latestVersionOnly', 'true'
        requiredBundles.each {
            // iu = installable unit
            iu "${it}"
            // iu "${it}.sources"
        }
        append true
    }
```

I confirm that this works fine in my local environment (and in an isolated docker container) with:

 -  a firewall rule enabled to block connection requests to https://download.eclipse.org
 -  fresh-started Gradle daemon after a `gradle clean` and a `gradle --stop`;

When I decided to serve the p2 files from an HTTP server though (example: `repo "http://some-server/p2-eclipse-4.9-201809060745/"`) I discovered that the `p2.mirror` ant task was trying to connect to eclipse's servers regardless:

```
feb 19, 2019 4:13:57 PM org.apache.http.impl.client.DefaultRequestDirector tryConnect
[p2.mirror] INFO: I/O exception (java.net.SocketException) caught when connecting to {}->http://www.eclipse.org:80: Permission denied: connect
```

After a bunch of these errors, the build *seems* to go fine but instead is just frozen/locked (I left the process running for about 15 mins, then I decided to `kill` it given the fact that there were no traces of CPU, Disk or Network activity):

```
...
[p2.mirror] INFO: I/O exception (java.net.SocketException) caught when connecting to {}->http://www.eclipse.org:80: Permission denied: connect
[p2.mirror] feb 19, 2019 4:15:00 PM org.apache.http.impl.client.DefaultRequestDirector tryConnect
[p2.mirror] INFO: Retrying connect to {}->http://www.eclipse.org:80
BUILD SUCCESSFUL

BUILD SUCCESSFUL
Total time: 1 minute 29 seconds
[still running]
```

Do you have any ideas of why this would happen?

**Comment by nedtwigg** [comment]
Goomph doesn't have much control over the `p2.mirror` ant task, we're just shelling out to vanilla eclipse.  It's possible there are some flags or system properties that eclipse will respect...  I would try to run the eclipse ant task without goomph and see if you get the same problem.  I expect that you will.  Then I'd explore the eclipse docs to see if you can find how to resolve it.  If you're able to accomplish that (to me that sounds hard but possible), it would be easy to incorporate that improvement into goomph.

An alternative would be to use your permissive personal box to create the maven repo, deploy that repo to a shared server, and then point all your day-to-day builds to the maven repo.  Not ideal, but easy to do.

If you're only using core eclipse plugins (ui, pde, jdt), as indicated in the little snippet that you pasted above, those are all available in mavencentral now.  Internally at DiffPlug, we have stopped grabbing our eclipse infrastructure from p2 and we're just grabbing at from mavencentral now.  docs here: https://diffplug.github.io/goomph/javadoc/3.17.4/com/diffplug/gradle/eclipse/MavenCentralPlugin.html

**Comment by niktekusho** [comment]
Sorry for lack of response. In the end, we started using your suggested approach which has been working fine.
