### ISSUE TITLE
example fails with Java 11 on Ubuntu 18.04

### ISSUE THREAD

**Issue by lennartfricke** [diffplug/goomph#99]
Running the ide task fails here on Ubuntu 18.04 with java 11 and gradle 5.2.1
I attached log files. There are exception concerning some class loader issues.

[1560754823763.log](https://github.com/diffplug/goomph/files/3295577/1560754823763.log)

[gradle.log](https://github.com/diffplug/goomph/files/3295581/gradle.log)

**Comment by nedtwigg** [comment]
Roger.  Goomph is untested past Java 8.  Happy to accept PR's to add support for this, but we at DiffPlug will not be leading this effort at this time.

**Comment by moley** [comment]
Hi, is there any chance to get this fixed in near future?

**Comment by nedtwigg** [comment]
Happy to take a PR to add support, and if it gets added we will add Java 11 to the test matrix to make sure it doesn't break.  However, at DiffPlug our plan is to stay on Java 8 probably until either Valhalla or Loom makes it into an LTS, so we will not take initiative on this in the near future.  Definitely lots of goodies in Java 11 that we like, no question, just not enough for the cost-benefit to work out for our usecases.

**Comment by nedtwigg** [comment]
`3.28.0` fixes some Java 11 issues. I'm closing this issue for now, but if it's still broken post info here and I'll reopen.
